name: lstream
services:
  app:
    build:
      context: ../..
      dockerfile: .docker/Dockerfile
      args:
        NODE_ENV:
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    volumes:
      - ../..:/workspace
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.zshrc:/root/.zshrc
      - /var/run/docker.sock:/var/run/docker.sock
      - claude:/root/.claude
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /workspace/app
    command: sleep infinity

volumes:
  claude:
